config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  root 'static_pages#home'
  get  '/login',     to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  resources :users, except: %i[new create]
  get  '/posts',     to: 'posts#index'
  get  '/posts/new', to: 'posts#new'
  post '/posts', to: 'posts#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :posts, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 6, maximum: 255 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    return unless logged_in?

    flash[:danger] = 'You Have already logged in'
    redirect_to posts_path
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user&.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_back_or posts_url
    else
      flash.now[:danger] = 'Oops! Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[edit index update destroy]
  before_action :correct_user, only: %i[edit update]
  before_action :member_user, only: %i[destroy]
  def new
    if logged_in?
      flash[:danger] = 'You have already logged in!'
      redirect_to posts_url
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Sign up successful!'
      redirect_to posts_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = 'Profile successfully updated.'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User successfully deleted.'
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email,
                                 :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end

  def current_user?(user)
    user == current_user
  end

  def member_user
    redirect_to(root_url) unless current_user.member?
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 

  <body>
    <header class='navbar fixed-top navbar-inverse'>
      <div class='container'>
          <%= link_to 'Members Only', root_path, id: 'logo', class: 'navbar-brand' %>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Home", root_path %></li>
               <li><%= link_to 'All Posts', posts_path %></li>
              <% if logged_in? %>
                <li><%= link_to 'Make a post', posts_new_path, method: :get %></li>
                <li><%= link_to 'All Members', users_path %></li>
                <li class='dropdown'>
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class='dropdown-menu'>
                    <li><%= link_to 'Profile' , user_path(current_user) %></li>
                    <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                    <li class='dropdown-divider'>
                      <li><%= link_to 'Log out', logout_path, method: :delete %></li>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
              <% end %>
            </ul>
          </nav>
      </div>
    </header>

    <div class='container'>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    
    </div>

    
    <%= yield %>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="col-md-6 col-md-offset-3">
    <%@posts.each do |post|%>
        <div class="post-container">
            <%if logged_in?%>
                <div class="author">
                    Author : <%=post.user.name%>
                </div>
            <%end%>
           
            <div>
                Title : <%=post.title%>
            </div>
            <div class="content-container">
                <%=post.content%>
            </div>
           
           
        </div>
    <%end%>
</div>

app/views/posts/new.html.erb
<%if @post.errors.any?%>
    <div class='container'>
        <% @post.errors.full_messages.each do |message| %>
            <%= content_tag(:div, message, class: "alert alert-danger") %>
        <% end %>
        
    </div>
<%end%>



<div class="col-md-5 col-md-offset-3">
<%= form_for @post do |f|%>
    <%=f.label :title , 'Title'%>
    <%=f.text_field :title , placeholder: 'Title', class: 'form-control'%>
    <%=f.label :content , 'Content'%>
    <%=f.text_area :content , placeholder: 'Content',class: 'form-control'%>
    <%= f.submit 'Post', class: 'btn btn-primary'%>
<%end%>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <div id='error_explanation'>
        <div class='alert alert-danger'>
        The form contains <%= pluralize(object.errors.count, 'error') %>
        </div>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <%end%>
        </ul>
    </div>
<% end%>

app/views/static_pages/home.html.erb
<%= provide(title: 'Home')%>
<div class='centerItem jumbotron'>
    <h1>Only For Members Of The Club</h1>
    <h2>Not yet a member?</h2>
    <%= link_to 'Register!', signup_path, class: 'btn btn-primary'%>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f|%>
  <%= render 'shared/errors', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>
  <%= f.label :email %>
  <%= f.email_field :email, placeholder: 'email', class: 'form-control' %>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: 'password', class: 'form-control' %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: 'confirm your password', class: 'form-control'%>
  <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

app/views/users/_user.html.erb
<li>
    <%= link_to user.name, user %>
    <% if current_user.member? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Sure you to delete?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, 'Edit your profile') %>
<%= provide(:url, user_path(@user)) %>
<%= provide(:button_text, 'Update profile') %>
<h1>Edit your profile</h1>
<div class='row'>
    <div class='col-md-4 col-md-offset-4'>
        <%= render 'form' %>
    </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>List Of All Users In The Club</h1>

<%= will_paginate %>
<ul class="users">
    <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<%= provide(:url, signup_path) %>
<%= provide(:button_text, 'Sign up') %>
<h1>Register</h1>
<div class='row'>
    <div class='col-md-4 col-md-offset-4'>
        <%= render 'form' %>
    </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name)%>
<h1>Posts by <%= @user.name %></h1>
<ol class='posts'>
    <% if @user.posts.any? %>
        <% @user.posts.each do |post|%>
            <li><%= link_to post.title, posts_path %></li>
        <% end %>
    <% end %>
</ol>